---
- name: spark installation
  hosts: all
  tasks:

  - name: Creating user 
    user:
      name:  ansible
      shell: /bin/bash
      groups: sudo 
      append: yes
      state: present
      create_home: True 

  - name: installing java
    package: 
      name: openjdk-8-jre-headless
      state: present
      update_cache: yes 
  - name: installing scala
    package:
      name: scala
      state: present

  - name: install unzip
    package:
      name: unzip
      state: present

  - name: downloading spark
    get_url: 
      url:  'https://downloads.apache.org/spark/spark-3.1.1/spark-3.1.1-bin-hadoop2.7.tgz'
      dest: ~/spark.tgz
      force: yes

  - name: creating archive
    file:
      path: /usr/local/spark
      state: directory
      force: yes
  - name: unarchive spark
    command: 'tar xvf ~/spark.tgz'
    tags: unarchive

  - name: moving files
    copy: 
      remote_src: True
      src: spark-3.1.1-bin-hadoop2.7
      dest: /usr/local/
  - name: profile spark
    command: "echo 'export PATH=/usr/local/spark/bin:$PATH' >> ~/.profile ; source ~/.profile"

  - name: copying configuring files
    copy:
      src: /usr/local/spark-3.1.1-bin-hadoop2.7/conf/spark-env.sh.template
      dest: /usr/local/spark-3.1.1-bin-hadoop2.7/conf/spark-env.sh
      remote_src: yes

  - name: editing file
    lineinfile:
      path: /usr/local/spark-3.1.1-bin-hadoop2.7/conf/spark-env.sh
      line: 'export SPARK_MASTER_HOST=159.65.47.69'

  - name: editing file
    lineinfile:
      path: /usr/local/spark-3.1.1-bin-hadoop2.7/conf/spark-env.sh
      line: 'export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre' 


    


     
    
