---
- name: spark installation
  hosts: localhost 
  tasks:
  - name: step1
    package:
      name: software_properties_common
      state: present

  - name: step2
    apt_repository:
      repo: ppa:webupd8team/java
      state: present

  - package:
      name: openjk-11-jdk
      state: present
