---
- name: spark installation
  hosts: all
  tasks:

  - name: Creating user 
    user:
      name:  ansible
      shell: /bin/bash
      groups: sudo 
      append: yes
      state: present
      create_home: True 
  - name: installing java
    package: 
      name: openjdk-8-jre-headless
      state: present
  - name: installing scala
    package:
      name: scala
      state: present
  - name: downloading spark
    get_url: 
      url: 'www.google.com' 
      dest: spark.tgz

     
    
